### ISSUE TITLE
Set an arg before calling a dependency

### ISSUE THREAD

**Issue by barchard** [QoboLtd/phake-builder#69]
Is it possible to set an arg before calling a dependency? I want to invoke `composer install` on a subdirectory of my project. Ideally, it would be done as a dependency in the Phake task. What are your thoughts on how best to utilize your awesome work here with a nested folder structure?

Thanks

**Comment by mamchenkov** [comment]
One way I can think of to accomplish this is to have another Phakefile in the sub-directory and call phake in there (using, for example, `doShellCommand`).  This way it will be similar to make and other build tools, which run recursively and re-build sub-directories.

If this approach doesn't work for you, maybe you could share some more information about your scenario.

Thanks.

**Comment by mamchenkov** [comment]
One other thing you can try (as as idea) is to use `before('some-task', function () { });`. Not sure it solves your problem, but I found it to be useful just recently, after a very long time of using `phake`. :)
